config/routes.rb
Rails.application.routes.draw do

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
  get 'home', to: 'home#index'
  end

  get 'backoffice', to: 'backoffice/dashboard#index' 
  

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :category
  belongs_to :member
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	enum role: [:full_access, :restricted_access]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def role_br
  	if self.role == 'full_access'
  		'Acesso Completo'
  	else
  		'Acesso Restrito'
  	end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates_presence_of :description
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	layout :layout_by_resource

  	protected
	
	# Layout per resource_name
	def layout_by_resource
	  if devise_controller? && resource_name == :admin
	    "backoffice_devise"
	  else
	    "application"
	  end
	end

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
   

  def index
  	@admins = Admin.all
  end

  def new
  	@admin = Admin.new
  end

  def create
  	@admin = Admin.new(params_admin)

    if @admin.save
      redirect_to backoffice_admins_path, notice: "O Administrador 
          (#{@admin.email}) foi salvo com sucesso! "
    else
      render :new   
    end

  end

  def edit
  	
  end

  def update

    passwd = params[:admin][:password]
    passwd_confirmation = params[:admin][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
      
    end

    if @admin.update(params_admin)
      redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi editado com sucesso! "
    else
      render :edit  
    end

  end

  def destroy

    admin_email = @admin.email

    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O Administrador (#{admin_email}) foi deletado com sucesso! "
    else
      render :index
    end

  end

  private

    def params_admin

      params.require(:admin).permit(:name, :email, :password, :password_confirmation)
      
    end

    def set_admin

          @admin = Admin.find(params[:id])
      
    end

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  
  before_action :set_category, only: [:edit, :update]
   

  def index
  	@categories = Category.all
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(params_category)

    if @category.save
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi salva com sucesso! "
    else
      render :new   
    end

  end

  def edit
  	
  end

  def update

    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi editada com sucesso! "
    else
      render :edit  
    end
  end

  private

    def params_category

      params.require(:category).permit(:description)
      
    end

    def set_category

          @category = Category.find(params[:id])
      
    end

end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController


  def index
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	
	before_action :authenticate_admin!

    layout "backoffice"

end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
 
  layout "site"

  def index
  	@categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", 
                locals: {action: "Editando Administrador"} %>

app/views/backoffice/admins/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Categorias</h1>
               
               <div class="panel panel-default">
                    <div class="panel-heading">
                        Listando Administradores
                        <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle pull-right", style:"margin-top: -5px" do %>
                            <i class="fa fa-plus"></i>                           
                        <% end %>
                    </div>
                
				<table class="table table-striped table-bordered table-hover">
                    <thead>
                    	
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Tipo de Acesso</th>
                           	<th></th>
                        </tr>
                    </thead>
                    <tbody>
                    	<% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.id %></td>
                            <td><%= admin.name %></td>
                            <td><%= admin.email %></td>
                            <td><%= admin.role_br %></td>
                            <td style="width: 81px">

                            <%= link_to edit_backoffice_admin_path(admin.id), class: "btn btn-primary btn-circle" do %>
                                <i class="fa fa-edit"></i>
                            <% end %>
                            <% if current_admin.id != admin.id %>
                                <%= link_to backoffice_admin_path(admin.id), method: :delete, class: "btn btn-danger btn-circle", data: {confirm: "Você deseja realmente excluir o administrador <b>(#{admin.email})</b>?"} do %>
                                <i class="fa fa-minus"></i>
                                <% end %>
                               <% else %>
                                 <%= link_to '#', class: "btn btn-danger btn-circle", disabled: "disabled" do %>
                                <i class="fa fa-minus"></i>
                                <% end %> 
                            <% end %>
                            </td>
                         </tr>
                       <% end %>
                    </tbody>
                </table>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form",
                 locals: {action: "Novo Administrador"} %>

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>

<% if @admin.errors.any? %>

    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <% @admin.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>

<% end %>
    
<div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
	<div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @admin]) do |f| %>
                <div class="form-group">
                    <label>Nome</label>
                    <%= f.text_field :name, class: "form-control", placeholder: "Nome do administrador" %>
                </div>
                <div class="form-group">
                    <label>E-mail</label>
                    <%= f.text_field :email, class: "form-control", placeholder: "E-mail do administrador" %>
                </div>
                <div class="form-group">
                    <label>Senha</label>
                    <%= f.password_field :password, class: "form-control",
                     placeholder: "Senha" %>
                </div>
                <div class="form-group">
                    <label>Confirmação da Senha</label>
                    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmação da senha" %>
                </div>    
        </div>
                <button type="submit" class="btn btn-default">Salvar</button>
            <% end %>
        </div>
    </div>
</div>
 

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", 
                locals: {action: "Editando Categoria"} %>

app/views/backoffice/categories/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Categorias</h1>
               
               <div class="panel panel-default">
                    <div class="panel-heading">
                        Listando Categorias
                        <%= link_to new_backoffice_category_path, class: "btn btn-success btn-circle pull-right", style:"margin-top: -5px" do %>
                            <i class="fa fa-plus"></i>                           
                        <% end %>
                    </div>
                
				<table class="table table-striped table-bordered table-hover">
                    <thead>
                    	
                        <tr>
                            <th>Id</th>
                            <th>Descrição</th>
                           	<th></th>
                        </tr>
                    </thead>
                    <tbody>
                    	<% @categories.each do |category| %>
                        <tr>
                            <td><%= category.id %></td>
                            <td><%= category.description %></td>
                            <td style="width: 81px">

                            <%= link_to edit_backoffice_category_path(category.id), class: "btn btn-primary btn-circle" do %>
                                <i class="fa fa-edit"></i>
                            <% end %>
                            <button type="button" disabled="disabled" class="btn btn-danger btn-circle"><i class="fa fa-minus"></i>
                            </button>
                            </td>
                         </tr>
                       <% end %>
                    </tbody>
                </table>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form",
                 locals: {action: "Nova Categoria"} %>

app/views/backoffice/dashboard/index.html.erb
    <h1 class="page-header">Dashboard</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BackOffice - SFM</title>

     
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track' => true %>
   
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    

    <div id="wrapper">
        <%= render partial: "layouts/backoffice_shared/navigation" %>


        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                     <%= yield %>

                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
</div>

    
    
    <% if notice %>    
        <script>
            $.notify("<%= notice %>", "success");
        </script>
    <% end %>  

    </body>

</html>

app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BackOffice - SFM</title>

     
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track' => true %>
   
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <%= yield %>
   
</body>

</html>

app/views/layouts/backoffice_shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">BackOffice - SFM</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li><%= current_admin.email %></li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                       
                          <%= link_to destroy_admin_session_path, method: :delete do %>
                              <i class="fa fa-sign-out fa-fw"></i> Sair
                          <% end %>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        
                        <li>
                            <%= link_to backoffice_path do %>
                            <i class="fa fa-dashboard fa-fw"></i> Dashboard
                            <% end %>
                        </li>
                        
                        <li>
                            <%= link_to backoffice_categories_path do %>
                            <i class="fa fa-th-list fa-fw"></i> Categorias
                            <% end %>
                        </li>
                        <li>
                            <%= link_to backoffice_admins_path do %>
                            <i class="fa fa-users fa-fw"></i> Administradores
                            <% end %>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop for Men</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track' => true %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'site', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    

</head>

<body>
    <%= render partial: "layouts/site_shared/navigation" %>
    <%= yield %>
    <%= render partial: "layouts/site_shared/footer" %>
</body>

</html>

app/views/layouts/site_shared/_footer.html.erb
 <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

app/views/layouts/site_shared/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Start Bootstrap</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>